engines:
  rubocop:
    enabled: true
  coffeelint:
    enabled: true
  bundler-audit:
    enabled: true

exclude_paths:
- spec/**/*
- vendor/**/*
- rails_autolink-1.1.6/**/*
- app/assets/javascripts/joyride/**/*
- app/assets/stylesheets/joyride/**/*
- app/assets/stylesheets/masonry/**/*
