require: rubocop-rspec

AllCops:
  RunRailsCops: true

  Include:
    - 'db/seeds.rb'

  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'rails_autolink-1.1.6/**/*'
    - 'app/assets/stylesheets/uh-styleguide/**/*'

Metrics/LineLength:
  Enabled: false

Documentation:
  Enabled: false
