require: rubocop-rspec

AllCops:
  RunRailsCops: true

  Include:
    - 'db/seeds.rb'

  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'

Metrics/LineLength:
  Enabled: false

Documentation:
  Enabled: false
