language: ruby

rvm:
 - 2.2.0

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_script:
  - psql -c 'create database test;' -U postgres

script:
 - bundle exec rake db:migrate --trace
 - RAILS_ENV=test bundle exec rake db:migrate --trace
 - bundle exec rake db:test:prepare
 - xvfb-run --server-args="-screen 0 1024x768x24"
 - bundle exec rspec -fd spec/

deploy:
  provider: heroku
  api_key: 214c2567-e0f5-47cb-a364-38af8ee0cced
  app: uhpeople
  on:
    repo: makroma/UHPeople
    branch: dev
  run: rake db:migrate

addons:
  code_climate:
    repo_token: c0f5911ac98f3e60f97b4ef9af39b43e664814f674bb939b344b9d2390da182a
