language: ruby
rvm:
- 2.2.3
before_install:
- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile
  --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- psql -c 'create database test;' -U postgres
script:
- bundle exec rake db:migrate --trace
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rspec -fd spec/
deploy:
  provider: heroku
  api_key:
    secure: AbnI4WdHf/NEWY2GeovuMkMeuZu2EOcPKXe5heczxhoCZHCeh4lHmiRm8o7Aw3XxCzHVUbiFHoOgOVC3XOI0qaSqzSppCiibAzJTK+YMVH8ffDY0AK0MkvaM1WbPcoMkGjUEqv4ShW73kLg3nS4lSnHqxcTpoe7QDStv0uDejZ4=
  app: uhpeople2
  on:
    repo: UHPeople/UHPeople
    branch: dev
  run: rake db:migrate
addons:
  code_climate:
    repo_token: c0f5911ac98f3e60f97b4ef9af39b43e664814f674bb939b344b9d2390da182a
