default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: postgres

development:
  <<: *default
  database: development-db

test:
  <<: *default
  database: test-db

production:
  <<: *default
  database: production-db
